"""create initial tables

Revision ID: 019965ce4ab8
Revises: 
Create Date: 2026-03-21 18:09:13.759395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '019965ce4ab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('retrieved_context', sa.Text(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('action_recommended', sa.Text(), nullable=False),
    sa.Column('critic_verdict', sa.Enum('approved', 'rejected', 'revision', name='criticverdict'), nullable=True),
    sa.Column('critic_score', sa.Float(), nullable=True),
    sa.Column('critic_notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity_in_stock', sa.Float(), nullable=False),
    sa.Column('reorder_threshold', sa.Float(), nullable=False),
    sa.Column('spoilage_risk', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'waitlist', 'completed', name='reservationstatus'), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('is_delivery', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentimenttype'), nullable=True),
    sa.Column('source', sa.Enum('google', 'in_person', 'zomato', 'swiggy', name='feedbacksource'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('orders')
    op.drop_table('reservations')
    op.drop_table('menu_items')
    op.drop_table('inventory')
    op.drop_table('decision_logs')
    # ### end Alembic commands ###
