"""add expenses table

Revision ID: 097476c556c0
Revises: 2a608f34ec0a
Create Date: 2026-07-07 13:54:27.895848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097476c556c0'
down_revision: Union[str, Sequence[str], None] = '2a608f34ec0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('rent', 'utilities', 'marketing', 'labor', 'other', name='expensecategory'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('recurrence', sa.Enum('one_time', 'daily', 'weekly', 'monthly', name='expenserecurrence'), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
