"""add action_queue table

Revision ID: 939bb1e4b5ac
Revises: 097476c556c0
Create Date: 2026-07-08 00:13:30.252187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939bb1e4b5ac'
down_revision: Union[str, Sequence[str], None] = '097476c556c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Enum('auto', 'approve_required', 'recommendation', name='actiontier'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'executed', 'rejected', 'expired', name='actionstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_queue')
    # ### end Alembic commands ###
