"""add_auth_tables_and_org_id_on_planning_runs

Revision ID: aae6e7dde10e
Revises: 7c7e6c2f3a10
Create Date: 2026-05-31 17:04:19.913386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae6e7dde10e'
down_revision: Union[str, Sequence[str], None] = '7c7e6c2f3a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_user_org')
    )
    op.add_column('planning_runs', sa.Column('org_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_planning_runs_created_at'), table_name='planning_runs')
    op.drop_index(op.f('ix_planning_runs_status'), table_name='planning_runs')
    op.drop_index(op.f('ix_planning_runs_target_date'), table_name='planning_runs')
    op.create_foreign_key(None, 'planning_runs', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planning_runs', type_='foreignkey')
    op.create_index(op.f('ix_planning_runs_target_date'), 'planning_runs', ['target_date'], unique=False)
    op.create_index(op.f('ix_planning_runs_status'), 'planning_runs', ['status'], unique=False)
    op.create_index(op.f('ix_planning_runs_created_at'), 'planning_runs', ['created_at'], unique=False)
    op.drop_column('planning_runs', 'org_id')
    op.drop_table('user_organizations')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
